FROM tomcat:8.0.44-jre8

LABEL org.label-schema.vendor="RPID" \
  org.label-schema.url="https://www.cordra.org/unconfiguredInstanceDownload" \
  org.label-schema.name="Cordra Server" \
  org.label-schema.version="1.0.7" \
  org.label-schema.docker.schema-version="1.0"

RUN apt-get update && apt-get install -y \
    curl 

RUN curl -o /tmp/cordra.zip https://www.cordra.org/unconfiguredInstanceDownload

ADD config /config

CMD ["catalina.sh", "run"]
