<%- | String[1] $handle_download_url | -%>
FROM library/alpine:3.1

LABEL org.label-schema.vendor="RPID" \
  org.label-schema.url="http://www.handle.net/download_hnr.html" \
  org.label-schema.name="Handle Server" \
  org.label-schema.version="0.0.1" \
  org.label-schema.docker.schema-version="1.0"

WORKDIR /handle

RUN apk add --update \
  curl \
  tar \
  && rm -rf /var/cache/apk/*

RUN curl <%= $handle_download_url %> \
  | tar xz --strip-components=1

# For debugging
CMD tail -f /dev/null
