FROM library/alpine:3.1
CMD /bin/sh -c "cat /srv/hs1/svr1/config.dct >/srv/hs1/svr1/cxrtest.txt"

LABEL org.label-schema.vendor="RPID" \
  org.label-schema.url="http://www.handle.net/download_hnr.html" \
  org.label-schema.name="Handle Server" \
  org.label-schema.version="0.0.1" \
  org.label-schema.docker.schema-version="1.0"
